[package]
name = "corundum_test"
version = "0.1.0"
authors = ["Seungmin Jeon <zzz845zz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
corundum = "0.2.2"
